adding a list of contributors
khannakshat7/GuruSkool pull request #6
Opened 2022-10-24 12:21 UTC by K0more

2022-10-25 05:45 UTC, khannakshat7 commented
@K0more You can create a MD file instead of html for contributors such as `Contributors.md`

2022-10-25 06:04 UTC, K0more commented
> @K0more You can create a MD file instead of html for contributors such as `Contributors.md`

alright 👍

2022-10-26 18:15 UTC, khannakshat7 requested changes

2022-10-26 18:15 UTC, khannakshat7 commented on Contributors.md
> +1. [Akshat Khanna](#akshat)
```suggestion
1. [Akshat Khanna](https://www.github.com/khannakshat7)
```

2022-10-26 18:15 UTC, khannakshat7 commented on Contributors.md
> +2. [Archit Khanna](#archit)
```suggestion
2. [Archit Khanna](https://www.github.com/k0more) 
```

2022-10-26 18:15 UTC, khannakshat7 commented on Contributors.md
> +        Twitter: @Khannakshat7
```suggestion
        Twitter: [@Khannakshat7](https://twitter.com/khannakshat7)
```

2022-10-26 18:15 UTC, khannakshat7 commented on Contributors.md
> +        LinkedIn: AkshatKhanna7
```suggestion
        LinkedIn: [AkshatKhanna7](https://www.linkedin.com/in/akshatkhanna7)
```

2022-10-26 18:15 UTC, khannakshat7 commented on Contributors.md
> +        github: khannakshat7
```suggestion
        github: [khannakshat7](https://github.com/khannakshat7)
```

2022-10-26 18:15 UTC, khannakshat7 commented on Contributors.md
> +        github: k0more
```suggestion
        github: [k0more](https://github.com/k0more)
```

2022-10-26 18:25 UTC, khannakshat7 requested changes

2022-10-26 18:25 UTC, khannakshat7 commented on Contributors.md
> +        Twitter: [@Khannakshat7](https://twitter.com/khannakshat7)
```suggestion
- Twitter: [@Khannakshat7](https://twitter.com/khannakshat7)
```

2022-10-26 18:25 UTC, khannakshat7 commented on Contributors.md
> +        LinkedIn: [AkshatKhanna7](https://www.linkedin.com/in/akshatkhanna7)
```suggestion
- LinkedIn: [AkshatKhanna7](https://www.linkedin.com/in/akshatkhanna7)
```

2022-10-26 18:25 UTC, khannakshat7 commented on Contributors.md
> +        github: [khannakshat7](https://github.com/khannakshat7)
```suggestion
- github: [khannakshat7](https://github.com/khannakshat7)
```

2022-10-26 18:25 UTC, khannakshat7 commented on Contributors.md
> +        github: [k0more](https://github.com/k0more)
```suggestion
- github: [k0more](https://github.com/k0more)
```

2022-10-26 18:36 UTC, khannakshat7 commented
LGTM! Great Work

2022-10-26 18:36 UTC, merged